### PR TITLE
Proxy Type

### PR DESCRIPTION
**Pull request by hughsaffar**
Integrated Proxy Type (SOCKS4 and SOCKS5)

### CODE REVIEW

**Comment by gsouf** [comment]
I'm wondering if it's better or not to replace the scheme instead of using both of scheme and type.

**Comment by TechAlchemistry** [comment]
I think too. It's not good. Because it will break backwards compatibility. I think it would be better to add a method setType() instead of changing the constructor.

**Comment by gsouf** [comment]
Changing the constructor is not a problem, the library is still in alpha, there is no backward compatibility awareness for the moment , it's rather that the scheme is irelevent in case of sock proxy

**Comment by TechAlchemistry** [comment]
It will be more better than new method.

**Comment by gsouf** [comment]
I merge and I will bring further changes

**Pull request merged**
