### PR TITLE
Added the HttpOnly flag

### PR DESCRIPTION
**Pull request by TechAlchemistry**

### CODE REVIEW

**Comment by gsouf** [comment]
Hi, 

Thanks for the contribution. However test suit is failling, can you update it before I merge.

More informations to run test suits and also about coding standards (see **tools** sections): https://github.com/serp-spider/core/blob/master/CONTRIBUTING.md#tools

This is the test that fails: https://github.com/serp-spider/core/blob/master/test/suites/TDD/Core/Cookie/CookieTest.php#L109

**Comment by TechAlchemistry** [comment]
Hi,

I create new pull request with correct test suits and code standart. Thank you for help :)

**Comment by gsouf** [comment]
Dont make a new PR, github is smart enough to understand the changes in one PR

**Comment by TechAlchemistry** [comment]
Ok. Thanks.

**Pull request closed without merging**
